version: '3.8'

services:

  postgres:
    image: postgres
    restart: always
    container_name: db-postgres-container
    environment:
      - POSTGRES_DB=bacesita
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@admin.com'
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "80:80"
    depends_on:
      - postgres  

  auth-microservice:
    build: 
      context: ./auth-microservice/auth-microservice
      dockerfile: Dockerfile
    container_name: auth-microservice-container
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - DATABASE_HOST=postgres
    command: ["/usr/wait-for-it.sh", "postgres:5432", "--", "npm", "run", "start:dev"]

  gateway-gira:
    build: 
      context: ./gateway-gira
      dockerfile: Dockerfile
    container_name: api-gateway-container
    ports:
      - "3005:3005"
    depends_on:
      - auth-microservice
    command: ["npm","run","start:dev"]

  # Puedes agregar otros microservicios y servicios adicionales aquí

volumes:
  postgres_data:
